services:
  db:
    image: postgres:15          
    container_name: weather_db  
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"             
    volumes:
      - postgres_data:/var/lib/postgresql/data 


  app:
    image: weather-service:latest 
    container_name: weather_app
    build: .                      
    depends_on:
      - db                        
    ports:
      - "8080:8080"             
    environment:

      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - OPENWEATHERMAP_API_KEY=${OPENWEATHERMAP_API_KEY}

volumes:
  postgres_data: