version: '3.8'

services:
  db:
    image: postgres:15          
    container_name: weather_db  
    environment:
      - POSTGRES_DB=weatherdb
      - POSTGRES_USER=marketting
      - POSTGRES_PASSWORD=your_password 
    ports:
      - "5432:5432"             
    volumes:
      - postgres_data:/var/lib/postgresql/data 


  app:
    image: weather-service:latest 
    container_name: weather_app
    build: .                      
    depends_on:
      - db                        
    ports:
      - "8080:8080"             
    environment:

      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/weatherdb

      - SPRING_DATASOURCE_USERNAME=marketting
      - SPRING_DATASOURCE_PASSWORD=
      - OPENWEATHERMAP_API_KEY=${OPENWEATHERMAP_API_KEY}

volumes:
  postgres_data: