CREATE TABLE current_weather (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    temperature DOUBLE PRECISION NOT NULL,
    humidity INT NOT NULL,
    wind_speed DOUBLE PRECISION NOT NULL,
    wind_direction INT NOT NULL,
    pressure INT NOT NULL,
    weather_main VARCHAR(255),
    weather_desc VARCHAR(255),
    sunrise TIMESTAMP,
    sunset TIMESTAMP,
    last_updated TIMESTAMP NOT NULL,
    city_id BIGINT NOT NULL UNIQUE,
    CONSTRAINT fk_city
        FOREIGN KEY(city_id) 
        REFERENCES cities(id)
);