CREATE TABLE forecasts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    forecast_date DATE NOT NULL,
    temperature DOUBLE PRECISION NOT NULL,
    wind_speed DOUBLE PRECISION NOT NULL,
    wind_direction INT NOT NULL,
    pressure INT NOT NULL,
    humidity INT NOT NULL,
    weather_main VARCHAR(255),
    weather_desc VARCHAR(255),
    rain_volume DOUBLE PRECISION,
    probability DOUBLE PRECISION, 
    city_id BIGINT NOT NULL,
    CONSTRAINT fk_forecast_city
        FOREIGN KEY(city_id) 
        REFERENCES cities(id)
);